# -*- coding: utf-8 -*-
"""min_euclid_distance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/nepatiess/e632011d693c4c48ccf29c0658d14fbf/min_euclid_distance.ipynb

Kütüphane
"""

import math
import matplotlib.pyplot as plt

print("---- EUCLID DISTANCE CALCULATOR AND PLOTTER ")

"""Noktaların kullanıcıdan alınması için bir fonksiyon"""

def get_number(prompt_message):
    while True:
        user_input = input(prompt_message)
        try:
            # Tries to convert the entered value to a float
            value = float(user_input)
            return value # If successful, return the number and exit the loop
        except ValueError:
            # Warns if the conversion fails (e.g., if a letter is entered)
            print("Error: Please enter only numbers instead of letters or words! (e.g., 3 or 4.5)")

"""Kullanıcıdan veri alınması"""

# Getting data from the user
print("\nEnter the coordinates of Point A (x1, y1):")
x1 = get_number("X1 value (Horizontal): ")
y1 = get_number("Y1 value (Vertical): ")

print("\nEnter the coordinates of Point B (x2, y2):")
x2 = get_number("X2 value (Horizontal): ")
y2 = get_number("Y2 value (Vertical): ")

"""Mesafenin hesaplanması"""

# Calculating the distance
distance = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

"""Sonucu terminale yazdırma"""

# Printing the result to the terminal
print("\n--- Result ---")
print(f"The Euclidean distance between A({x1}, {y1}) and B({x2}, {y2}) is: {distance:.2f}")

"""Grafik çizim aşaması"""

print("Generating plot... Please check the newly opened window.")

plt.figure(figsize=(8, 6))

# Plot Point A and Point B
plt.plot(x1, y1, 'ro', markersize=8, label=f'Point A ({x1}, {y1})')
plt.plot(x2, y2, 'bo', markersize=8, label=f'Point B ({x2}, {y2})')

# Plot the main distance (Black line)
plt.plot([x1, x2], [y1, y2], 'k-', linewidth=2, label=f'Distance: {distance:.2f}')

# Dashed lines to show the right triangle logic
plt.plot([x1, x2], [y1, y1], 'g--', linewidth=1.5, label='Horizontal Difference')
plt.plot([x2, x2], [y1, y2], 'm--', linewidth=1.5, label='Vertical Difference')

# Plot settings
plt.title('Euclidean Distance Between Entered Points', fontsize=10, fontweight='bold')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.grid(True, linestyle=':', alpha=0.7)
plt.legend(loc='best')

# Show the plot on the screen
plt.show()
